language: node_js
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js: 
  - 10
install: 
  - npm install
script: 
  - node lighthouse.js